[tox]
skip_missing_interpreters = true
envlist = py{38,39,310,311}, lint{38}, format

[testenv]
setenv = PYTHONPATH = {toxinidir}
extras = dev
commands =
    pytest --cov bcc/
    coverage report -m

[testenv:lint]
setenv = PYTHONPATH = {toxinidir}
extras = dev
commands =
    pylint bcc

[testenv:format]
commands =
     isort bcc/
     yapf -ir bcc/

[isort]
line_length = 79
multi_line_output = 2
use_parentheses = False

[coverage]
omit = bcc/tests/*

[coverage:html]
title = Basis BCC Coverage Report
